# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MenuWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from FFTWindow import Ui_MainWindow as Ui_MainWindow_FFT


class Ui_MainWindow(object):
    def on_click_fft(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_FFT()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnFFT = QtWidgets.QPushButton(self.centralwidget)
        self.btnFFT.setGeometry(QtCore.QRect(40, 80, 191, 181))
        self.btnFFT.setObjectName("btnFFT")
        self.btnFFT.clicked.connect(self.on_click_fft)
        self.btnLPF = QtWidgets.QPushButton(self.centralwidget)
        self.btnLPF.setGeometry(QtCore.QRect(310, 80, 191, 181))
        self.btnLPF.setObjectName("btnLPF")
        self.btnMDF = QtWidgets.QPushButton(self.centralwidget)
        self.btnMDF.setGeometry(QtCore.QRect(560, 80, 191, 181))
        self.btnMDF.setObjectName("btnMDF")
        self.btnWVL = QtWidgets.QPushButton(self.centralwidget)
        self.btnWVL.setGeometry(QtCore.QRect(310, 310, 191, 181))
        self.btnWVL.setObjectName("btnWVL")
        self.btnVAD = QtWidgets.QPushButton(self.centralwidget)
        self.btnVAD.setGeometry(QtCore.QRect(40, 310, 191, 181))
        self.btnVAD.setObjectName("btnVAD")
        self.btnEVA = QtWidgets.QPushButton(self.centralwidget)
        self.btnEVA.setGeometry(QtCore.QRect(560, 310, 191, 181))
        self.btnEVA.setObjectName("btnEVA")
        self.lbFFT = QtWidgets.QLabel(self.centralwidget)
        self.lbFFT.setGeometry(QtCore.QRect(80, 270, 121, 16))
        self.lbFFT.setObjectName("lbFFT")
        self.lbLPF = QtWidgets.QLabel(self.centralwidget)
        self.lbLPF.setGeometry(QtCore.QRect(370, 270, 121, 16))
        self.lbLPF.setObjectName("lbLPF")
        self.lbMDF = QtWidgets.QLabel(self.centralwidget)
        self.lbMDF.setGeometry(QtCore.QRect(630, 270, 121, 16))
        self.lbMDF.setObjectName("lbMDF")
        self.lbVAD = QtWidgets.QLabel(self.centralwidget)
        self.lbVAD.setGeometry(QtCore.QRect(80, 500, 121, 16))
        self.lbVAD.setObjectName("lbVAD")
        self.lbWAV = QtWidgets.QLabel(self.centralwidget)
        self.lbWAV.setGeometry(QtCore.QRect(390, 500, 121, 16))
        self.lbWAV.setObjectName("lbWAV")
        self.lbEVA = QtWidgets.QLabel(self.centralwidget)
        self.lbEVA.setGeometry(QtCore.QRect(630, 500, 121, 16))
        self.lbEVA.setObjectName("lbEVA")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnFFT.setText(_translate("MainWindow", "FFT"))
        self.btnLPF.setText(_translate("MainWindow", "LPF"))
        self.btnMDF.setText(_translate("MainWindow", "MDF"))
        self.btnWVL.setText(_translate("MainWindow", "WAVELET"))
        self.btnVAD.setText(_translate("MainWindow", "VAD"))
        self.btnEVA.setText(_translate("MainWindow", "EVALUATE"))
        self.lbFFT.setText(_translate("MainWindow", "Fast Fourier Transform"))
        self.lbLPF.setText(_translate("MainWindow", "Low Pass Filter"))
        self.lbMDF.setText(_translate("MainWindow", "Median Filter"))
        self.lbVAD.setText(_translate("MainWindow", "Voice Active Detection"))
        self.lbWAV.setText(_translate("MainWindow", "Wavelet"))
        self.lbEVA.setText(_translate("MainWindow", "Evaluation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
